### ISSUE TITLE
doesn't work in LinuxSampler

### ISSUE THREAD

**Issue by grammoboy2** [sfzinstruments/SalamanderGrandPiano#1]
Caching initial samples...sfz::Engine error: Failed to load instrument, cause: /home/user/linuxaudio/SalamanderGrandPiano/Data/Samples/harmLA0.flac: Can't get sample info: System error : No such file or directory

Something with the Data folder and path

**Comment by redtide** [comment]
It seems like there is some problem to resolve the [default_path] there, both SalamanderGrandPiano and [MatsHelgesson.MaestroConcertGrandPiano] loads correctly here in Sforzando and current sfizz (develop branch).
Note also that these instruments might use some unsupported SFZ2/ARIA opcodes.

[default_path]: https://sfzformat.com/opcodes/default_path
[MatsHelgesson.MaestroConcertGrandPiano]: https://github.com/sfzinstruments/MatsHelgesson.MaestroConcertGrandPiano/issues/3

**Comment by kinwie** [comment]
From the error message, it seems LinuxSampler handles multiple-level of #include in a different way, as the "Samples" folder should not be read under "Data" folder.
The #include opcode itself is ARIA's origin. So, this issue should be suitable to be mentioned at the LinuxSampler community for how it handle instruments formatted this way using ARIA Extensions.

**Comment by james-sounds-crazy** [comment]
Hello, 

It appears the issue owner abandoned this. 
Recommended for closure

**Comment by redtide** [comment]
Each sampler can implement a different number of opcodes and having different level of sfz compatibility, so it's possible that these instruments might work partially or not at all with some software.
@kinwie maybe we should be more clear about this in READMEs? If yes I leave this open as reminder.

**Comment by kinwie** [comment]
Yeah I think so.
Even the explicit info for the ARIA contained in the header of the sfz file, I guess it's not enough to get people to notice it.
I'll add some lines later to those sfz README (maybe all, but one by one) to note the compatibility issue.

**Comment by kinwie** [comment]
Added notes to warned users about compatibility and opcodes support issue.

**Comment by redtide** [comment]
Let's close it then.
