### ISSUE TITLE
Sustained Notes on Several Keys

### ISSUE THREAD

**Issue by james-sounds-crazy** [sfzinstruments/SalamanderGrandPiano#2]
Comments: Great work guys! Love this sfz.!

**Issue:**
Several keys do not decay as expected upon release.
Keys from F6 to  Bb6 plays sustained notes when the damper pedal _**is not**_ depressed

**Tested:**
Other keys are working as expected.
Loaded other soundfonts/sfzs. Did not experience sustained notes on the specified keys.

**Setup:**
Salamander Grand Piano V3.sfz  version August ‎23, ‎2020
Sforzando player
Win 10
i5 4th gen
8G RAM
1 TB HDD

**Comment by kinwie** [comment]
Hi, thanks for your comment. The original samples author did great job sampling and share this piano for free. We should thanks him also!

Actually, the sustained high notes is the real-behavior of a real grand piano. Is that what bothering you?
What do you think for any suggestion?

**Comment by james-sounds-crazy** [comment]
Hi kinwie, Thanks for following up on this.

As mentioned previously, I've loaded other sfzs to test. That includes the original sfz by Alexander Holm.  In these sfz, I did not experienced sustained notes on any of the keys upon release with no damper pedal applied. This is what was expected.

>Actually, the sustained high notes is the real-behavior of a real grand piano. Is that what bothering you?

I disagree, the F6 to Bb6  should not be sustained after the key has been released with no damper pedal applied. Although they are high notes, B6, C7 all the way to the last key (C8) do not play sustain notes after key has been released with no damper pedal applied.

Please see the red boxed keys. These are the only keys playing sustained notes after key has been released with no damper pedal applied. Can you find where in the code, that could cause this?
![sustained_keys](https://user-images.githubusercontent.com/90507310/133851256-a085b414-4781-4c56-aff3-59622f68a315.jpg)

**Comment by kinwie** [comment]
I just check it and okay I understand what you mean now. I think I changed the release opcode to one_shot mode in the past and it doesn't work well with the samples at F-Bb6. So I just change it back to use ampeg_release like the original version, and also did some revert back to the hard-coded sustain cc number.

If you still feel those notes too sustained, you can easily adjust it later.
Hope I set it better now. Thanks for your suggestion!

**Comment by james-sounds-crazy** [comment]
Hi kinwie, thanks for taking time for this project.
I downloaded 2021.09.20 version (latest) , set it up, and tested it to the best of my abilities.  As far as I can tell, the keys  F6 to Bb6 are now behaving like the rest of the keys. I consider this issue closed
