### ISSUE TITLE
Sound played on meta-actions like moving the play head

### ISSUE THREAD

**Issue by rohanlean** [sfzinstruments/SalamanderGrandPiano#4]
When used with sfizz 1.1.1 in Ardour 6.9, actions like moving the play head or muting a MIDI track that feeds the instrument result in a sound (maybe the lid closing?).  I would prefer for such meta-actions to be silent, and for the piano to only make noise when explicitly asked to.  At least there should be no extraneous sound on editing actions.  A sound after loading for example would be alright, perhaps.

**Comment by kinwie** [comment]
Afair, salamander piano doesn't have lid noise samples (only Maestro grand has it).
I never experienced this issue nor heard from other users yet.
So maybe like your previous issue, that it might be a bug with sfizz use in Ardour?

**Comment by rohanlean** [comment]
Of the instruments that I have tried Salamander is the only one that has this issue, which is why I have posted here first.

I think you may be onto something though.  Looking at the MIDI messages, I see Damper Pedal Off (0x4000) and All Notes Off (0x7B00) being sent on all channels.  So what I am hearing is presumably the sound of 16 damper pedals being released.  

Oddly enough this does not happen when I use aux-send to route the tracks to the piano.

I do not know whether sending these messages is appropriate, but I will make some enquiries.

**Comment by james-sounds-crazy** [comment]
Hi,

I tested this Salamander Grand on Plogue, loaded a midi file, move the play head around....
No such sound or lid closing...   
No issues with Salamander Grand.

Therefore this issue should be closed.

Also, debugging Ardour issues is beyond the scope of this project

**Comment by kinwie** [comment]
Yes, this is more to the host issue rather than the sfz file.
This has been reported to sfizz issues tracker and handled there.
So I close this one now.
