### ISSUE TITLE
sfzlint issues

### ISSUE THREAD

**Issue by kmturley** [sfzinstruments/SalamanderGrandPiano#9]
There is a tool for checking sfz files:
https://github.com/jisaacstone/sfzlint

When running the command:
```
sfzlint .
```

This is the output:
```
salamander-grand-piano.sfz:59:1:W unknown opcode (amp_veltrack_onccN)
salamander-grand-piano.sfz:74:10:E error loading include, Unexpected token Token('VARNAME', 'lovel') at line 3, column 36.
Expected one of: 
        * _NL
Previous tokens: [Token('_WSI', ' ')]

salamander-grand-piano.sfz:80:10:E error loading include, Unexpected token Token('VARNAME', 'lovel') at line 3, column 36.
Expected one of: 
        * _NL
Previous tokens: [Token('_WSI', ' ')]

salamander-grand-piano.sfz:95:24:W 200 not in range 0 to 100 (amplitude_onccN)
salamander-grand-piano.sfz:100:23:W 200 not in range 0 to 100 (amplitude_onccN)
salamander-grand-piano.sfz:111:22:W 200 not in range 0 to 100 (amplitude_onccN)
salamander-grand-piano.sfz:60:1:W curvecc opcode is not in the spec
salamander-grand-piano.sfz:63:1:W curvecc opcode is not in the spec
```

Can you check you are following recommended formatting for sfz files?

Thanks!

**Comment by redtide** [comment]
the question is also: is the linter in sync with the specs? When @jisaacstone wrote this tool the sfzformat db was still a work in progress, so some things might be missing or even missing/wrong on the db itself. AFAIK you are the first one I saw giving testing feedback on it.

**Comment by kinwie** [comment]
Hi,

When ARIA Engine landed on sfz format, everything's exploded. The old specs expanded unofficially and barely/properly undocumented because it was exclusive to ARIA only. Example, I even often used amplitude range to 800 or 1000, not has to be in the range of  0 - 100. SFZFormat.com exist to documenting everything and these last two years it's already updated with a lot of new information, but still need a lot more updated infos. Sfizz is supposed to surpass ARIA's implementation and if you find an opcode is not working, I suggest you to also open an issue in sfizz issue tracker so the devs can notice and fix it.

Amp_veltrack_onccN is one of opcodes that I've suggest for sfizz to be implemented last year. Iirc, it's done, but if it's still not working, you should reported an issue to them. I am not daily using sfizz so lot of stuff not in my watch.

If a tool for checking sfz does exist, it needs to be reliable, then the dev need to do a lot of homework, like we did cracking the mysteries of sfz. I also suggest you to notify the dev for what's needed to be updated.

**Comment by kinwie** [comment]
This is the opcode request of `amp_veltrack_onccN` and the gang that I suggested for sfizz. It has been closed, so I supposed it's done.

https://github.com/sfztools/sfizz/issues/483

**Comment by kinwie** [comment]
Technical explanation for `amplitude_onccN=200`

It's a volume control,
0 dB at 50% or CC value 64 in sfizz.

Turned it down to 0% or CC value 0, goes silent.
Turned it up to 100% or CC value 127, boost the volume to +6 dB.

So user can lowering the volume as usual, or raise the volume louder.
With amplitude value 100, you can only lowering the volume.
ARIA didn't clamp that value and it's useful when needed.

Note:
sforzando shows %
sfizz shows CC value

**Comment by kinwie** [comment]
@redtide 
Since this issue is not relevant to this repo, should we closed it or?

**Comment by redtide** [comment]
I think so, in the end the OP just asked to check about those warnings/errors. If there is nothing wrong or missing to document I guess we can close it. I'll wait for jisaacstone feedback to see how to manage some sfzformat db related problems later on.

**Comment by kmturley** [comment]
Sfzlint supports multiple specs:
```
ver_mapping = {
    None: 'unknown',
    'SFZ v1': 'v1',
    'SFZ v2': 'v2',
    'ARIA': 'aria',
    'LinuxSampler': 'linuxsampler',
    'Cakewalk': 'cakewalk',
    'Cakewalk SFZ v2': 'cakewalk_v2',
}
```
https://github.com/jisaacstone/sfzlint/blob/faaf295aed7fcbec2c2718b38d412a723fc7431a/sfzlint/spec.py#L12

This value can be sent to the command line as an argument:
https://github.com/jisaacstone/sfzlint/blob/master/sfzlint/cli.py#L23

Such as:
```
sfzlint . --spec-version=aria
```

Would that solve the issue? I'm not familiar with individual opcodes. So I don't know which spec you are using for this repo?

**Comment by redtide** [comment]
I'm sorry, I think asking here will not help since it has to do with the usage of the tool, you could "move" it on sfzlint project as an issue question instead. If you do, please mention this issue as reference.

**Comment by kmturley** [comment]
I think this is a relevant issue to this repo. sfzlint uses the syntax.yml file from sfzformat:
https://github.com/sfzformat/sfzformat.github.io/blob/source/_data/sfz/syntax.yml

I checked this repo using all available spec versions:
`--spec-version [{unknown,v1,v2,aria,linuxsampler,cakewalk,cakewalk_v2`

The commands used are:
```
sfzlint . --spec-version=unknown
sfzlint . --spec-version=v1
sfzlint . --spec-version=v2
sfzlint . --spec-version=aria
sfzlint . --spec-version=linuxsampler
sfzlint . --spec-version=cakewalk_v2
```

They all return errors. So my question is:
Which spec version are you writing Salamandar .sfz files for?

Once I know that, I can find whether there is an issue with sfzlint or sfzformat. But without that, you could be using opcodes from different specs and the tools are actually reporting correctly?

**Comment by redtide** [comment]
The versions are specified in the readme already, there is no such spec here, those are mostly categories used in the db internally.
